sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker pull quay.io/keboola/aws-cli
  - make build

script:
  - make test

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true