FROM gliderlabs/alpine:3.4
VOLUME /mnt/routes
EXPOSE 80

ENV GOPATH /go
RUN apk-install go build-base git mercurial ca-certificates
COPY . /go/src/github.com/ruguoapp/logspout
WORKDIR /go/src/github.com/ruguoapp/logspout
RUN go get
CMD go get \
	&& go build -ldflags "-X main.Version dev" -o /bin/logspout \
	&& exec /bin/logspout
